name: 'Assignment Corrector'
description: 'Evaluates your assignment and returns the grade'
inputs:
  programming-language:
    description: 'The selected programming language'
    required: true
  answer-location:
    description: 'The url where the zip with every answer is located'
    required: true
outputs:
  time:
    description: 'The time we received your file'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.programming-language }}
    - ${{ inputs.answer-location }}
